import * as z from 'zod/v4';

const id = z.string().regex(/^[\w-]{1,100}$/), revision = z.number().int().nonnegative();
const profile = z.object({ name: z.string().min(1).max(100), description: z.string().max(10000), tags: z.string().max(300).default('') });
const template = z.object({ name: z.string().min(1).max(100), description: z.string().max(500).default(''), prompt: z.string().min(1).max(20000) });
const series = z.object({ title: z.string().min(1).max(160), premise: z.string().min(1).max(10000), genre: z.string().max(300).optional(), tone: z.string().max(1000).optional(), world: z.string().max(10000).optional(), episodeCount: z.number().int().min(1).max(50).optional(), minChars: z.number().int().min(100).max(20000).optional(), maxChars: z.number().int().min(100).max(30000).optional(), countSpaces: z.boolean().optional(), characterIds: z.array(id).max(30).optional(), videoTemplateId: id.optional(), archived: z.boolean().optional() });
const memory = z.object({ summary: z.string().max(1800), facts: z.array(z.object({ subject: z.string().max(120), relation: z.string().max(120), object: z.string().max(500), evidence: z.string().max(1200) })).min(1).max(40), introduced: z.array(z.object({ key: z.string().max(100), title: z.string().max(160), description: z.string().max(1000), evidence: z.string().max(1200), payoffEpisode: z.number().int().nullable().optional() })).max(12), developments: z.array(z.object({ threadId: id, action: z.enum(['advance', 'resolve']), description: z.string().max(1200), evidence: z.string().max(1200) })).max(24) });
const graph = z.object({ title: z.string().max(160).optional(), nodes: z.array(z.object({ id, kind: z.enum(['image', 'video']), prompt: z.string().min(1).max(20000), templateId: id.optional(), characterIds: z.array(id).max(3).optional(), x: z.number().finite().optional(), y: z.number().finite().optional() })).min(1).max(100), edges: z.array(z.object({ source: id, target: id })).max(200) });
const def = (description, shape, readOnlyHint = false) => ({ description, inputSchema: z.object(shape), annotations: { readOnlyHint, destructiveHint: false, idempotentHint: readOnlyHint, openWorldHint: !readOnlyHint } });

export const studioToolDefinitions = {
  studio_persona_catalog: def('대화 가능한 공개 작품 캐릭터와 내 캐릭터, 연결된 작품의 완료 회차를 조회합니다. 시트 제작 도우미와 별개의 인물 역할 대화입니다.', {}, true),
  studio_persona_conversations: def('현재 계정의 캐릭터 대화방 목록을 읽습니다. 다른 계정이나 방문자의 기록은 포함하지 않습니다.', {}, true),
  studio_persona_conversation: def('저장한 캐릭터 대화 기록과 revision을 읽습니다.', { id }, true),
  studio_persona_start: def('선택한 캐릭터와 새 대화방을 저장합니다. 생성 호출은 하지 않습니다. public은 공개 작품 1화 기본, workspace는 시나리오를 선택하면 완료한 throughEpisode까지의 원고·그래프를 시작 시점에 고정합니다. 원고를 수정하지 않습니다.', { source: z.enum(['public', 'workspace']), characterId: id, scenarioId: id.optional(), throughEpisode: z.number().int().min(0).max(50).optional() }),
  studio_persona_send: def('캐릭터의 성격과 고정한 작품 맥락, 최근 대화로 실제 AI 답변을 생성하고 문답을 저장합니다. 비용 발생 가능. 최신 revision과 고유 requestId를 사용하고 네트워크 재시도에는 같은 requestId와 메시지를 재사용하세요. 전체 기록은 보관하나 모델은 최근 최대20개 메시지만 참고합니다. 원작이나 그래프를 변경하지 않습니다.', { id, revision, requestId: z.string().uuid(), message: z.string().trim().min(1).max(2000) }),
  studio_persona_remove: { ...def('사용자가 요청한 대화방과 기록을 삭제합니다. 최신 revision 필요. 원고와 캐릭터는 보존합니다.', { id, revision }), annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false } },
  studio_workspace: def('캐릭터·제작 보드·시나리오 목록과 사용 순서를 읽습니다. 변경이나 생성은 하지 않습니다.', {}, true),
  studio_templates: def('캐릭터 시트 또는 영상 템플릿을 조회/저장합니다. 기본 영상: animation, live-action. 기본 캐릭터: identity-sheet, anime-design. 기본 템플릿은 새 이름으로 복사합니다.', { kind: z.enum(['character', 'video']), operation: z.enum(['list', 'save']), template: template.optional(), id: id.optional(), updatedAt: z.string().optional() }),
  studio_video_template_chat: def('사용자와 대화하여 재사용할 애니메이션/실사 영화 스타일을 설계합니다. 반환된 template은 studio_templates로 저장해야 합니다.', { message: z.string().min(1).max(6000), template: template.optional() }),
  studio_character_chat: def('캐릭터 사진 또는 유형에 대한 대화로 캐릭터 시트를 준비합니다. ready=true 이후 사용자 생성 의사를 확인하고 studio_character_generate를 호출합니다.', { mode: z.enum(['photo', 'new']), templateId: id, message: z.string().max(4000), referenceImage: z.string().max(100).optional(), profile: profile.optional(), settings: z.object({ type: z.string().max(1000).optional(), age: z.string().max(1000).optional(), style: z.string().max(1000).optional(), outfit: z.string().max(1000).optional(), purpose: z.string().max(1000).optional(), layout: z.string().max(1000).optional() }).optional(), messages: z.array(z.object({ role: z.enum(['user', 'assistant']), content: z.string().max(6000) })).max(16).optional() }),
  studio_upload_image: def('사용자가 제공한 PNG/JPEG/WebP 참고 이미지(data URL, 최대6MB)를 작업실에 저장합니다. 서버 파일 경로나 외부 URL은 받지 않습니다.', { data: z.string().max(8500000) }),
  studio_character_generate: def('사용자가 요청한 실제 캐릭터 시트 이미지를 생성합니다. 유료 모델을 호출할 수 있습니다. 설정 검토 후 confirmed=true. 반환된 작업을 studio_job으로 조회하고 완료 후 studio_character_register로 등록합니다. 같은 요청 재조회에는 동일 idempotencyKey를 사용하세요.', { confirmed: z.literal(true), idempotencyKey: z.string().min(8).max(100), templateId: id, profile, prompt: z.string().min(1).max(20000), referenceImage: z.string().max(100).optional() }),
  studio_character_register: def('완료된 시트 이미지 작업을 캐릭터 라이브러리에 등록합니다. 같은 jobId로 재호출해도 중복 등록하지 않습니다.', { jobId: id, profile: profile.optional() }),
  studio_scenario: def('연속 시나리오 생성/조회/설정 수정. 먼저 전체 화수, 회차 최소·최대 글자 수, 영상 템플릿, 캐릭터를 정합니다. 수정에는 최신 revision이 필요합니다.', { operation: z.enum(['list', 'read', 'create', 'update']), id: id.optional(), revision: revision.optional(), values: series.partial().optional() }),
  studio_story_write: def('전체 플롯 → 1화부터 화별 플롯 → 1화부터 상세 원고 순으로 직접 저장합니다. 모든 플롯 완료 후 상세 원고를 저장할 수 있습니다. memory의 evidence는 해당 본문에 존재하는 정확한 인용이어야 합니다. 최소 글자 수 또는 기억 검증 미달은 완료되지 않습니다. 앞 화 변경 시 뒤 화는 stale 처리됩니다.', { id, revision, stage: z.enum(['overall', 'plot', 'content', 'limits']), episodeNumber: z.number().int().min(1).max(50).optional(), title: z.string().max(160).optional(), plot: z.string().max(20000).optional(), content: z.string().max(60000).optional(), memory: memory.optional(), minChars: z.number().int().min(100).max(20000).optional(), maxChars: z.number().int().min(100).max(30000).optional() }),
  studio_story_generate: def('설정된 AI로 다음 단계 또는 남은 전체 시나리오를 순차 생성합니다. 글자 수·기억 근거 검증 실패 시 멈춥니다. 유료 모델 사용 가능. jobId로 조회하며 같은 작품의 진행 중 요청은 재사용합니다.', { id, revision, all: z.boolean().default(false), instruction: z.string().max(4000).default('') }),
  studio_story_context: def('이전 화의 사실·인물 상태·미회수/회수된 떡밥을 근거와 그래프 경로로 검색합니다. beforeEpisode 이전의 유효한 화만 검색합니다. 미래나 수정이 필요한 원고는 제외됩니다.', { id, beforeEpisode: z.number().int().min(1).max(51).optional(), query: z.string().max(4000).default(''), entities: z.array(z.string().max(120)).max(30).default([]), limit: z.number().int().min(1).max(40).default(16) }, true),
  studio_story_graph: def('시나리오의 저장된 인물·사실·회차·복선·회수 관계 그래프를 읽습니다. active=false인 노드는 과거 수정 이력으로 검색에서 제외됩니다.', { id }, true),
  studio_episode_production: def('완성된 화를 제작 보드로 연결합니다. 이미 연결한 화는 기존 콘텐츠를 반환합니다.', { id, revision, episodeNumber: z.number().int().min(1).max(50) }),
  studio_episode_nodes: def('완성된 화를 AI가 장면으로 나누고 선택한 영상 템플릿을 적용하여 이미지 → 영상 노드 쌍을 만듭니다. 실제 미디어 생성은 studio_graph_run으로 별도 실행합니다. 반환된 jobId로 조회하세요.', { id, revision, episodeNumber: z.number().int().min(1).max(50), instruction: z.string().max(4000).default('') }),
  studio_graphs: def('웹 이미지·영상 제작 화면과 공유하는 노드 작업실 목록 또는 특정 그래프를 읽습니다.', { sessionId: id.optional() }, true),
  studio_graph_save: def('대화로 이미지/영상 노드와 연결을 만듭니다. templateId 및 characterIds로 스타일과 시트를 고정합니다. 영상에 연결할 부모는 이미지 하나입니다. 기존 그래프 수정은 전체 노드/연결 및 최신 graphVersion이 필요합니다.', { sessionId: id.optional(), graphVersion: revision.optional(), ...graph.shape }),
  studio_graph_run: def('선택 노드의 이미지 또는 영상을 실제 생성합니다. 비용 발생 가능. 앞 이미지 노드를 먼저 완료해야 합니다. graphVersion과 고유 idempotencyKey가 필요합니다. 반환 jobId를 조회하며 접수 응답이 끊겨도 새 요청으로 재생성하지 마세요.', { sessionId: id, nodeId: id, graphVersion: revision, idempotencyKey: z.string().min(8).max(100) }),
  studio_job: def('스토리·장면·미디어 작업 진행/결과를 조회합니다. 미디어 이력 조회는 이미지를 재생성하지 않습니다. id가 없으면 최근 작업 목록. pause=true는 현재 스토리 생성 단계를 저장한 후 멈춥니다.', { id: id.optional(), pause: z.boolean().default(false) }),
};
