-- Generated by node database/create-demo-seed.mjs. Demo accounts cannot log in.
-- Apply only to a fresh development database, after 001_schema.sql.
BEGIN;
SET LOCAL search_path = snowlink, public;
INSERT INTO users (id, username, role) VALUES ('954cca66-f6db-5aaa-8ec1-c86d875a031c', 'demo.moon-writer', 'demo') ON CONFLICT DO NOTHING;
INSERT INTO creator_profiles (user_id, handle, display_name, bio, tagline, is_public, is_demo) VALUES ('954cca66-f6db-5aaa-8ec1-c86d875a031c', 'moon-writer', '서월', '조용한 도시와 사라진 기억을 소재로 판타지 소설과 캐릭터를 만드는 가상 창작자입니다.', '밤에만 도착하는 이야기를 씁니다.', true, true) ON CONFLICT DO NOTHING;
INSERT INTO workspaces (id, owner_id, name) VALUES ('c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '954cca66-f6db-5aaa-8ec1-c86d875a031c', '서월의 목업 작업실') ON CONFLICT DO NOTHING;
INSERT INTO assets (id, workspace_id, storage_key, mime_type, width, height, source, provenance) VALUES ('806f50da-26c4-5895-862a-cae69df1e772', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 'showcase/moon-post.png', 'image/png', 1536, 1024, 'demo', '{"generatedWith":"image_gen","fictional":true}') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, role) VALUES ('4278ea09-e3ba-595e-81ff-dbf952a35ed0', 'demo.glass-garden', 'demo') ON CONFLICT DO NOTHING;
INSERT INTO creator_profiles (user_id, handle, display_name, bio, tagline, is_public, is_demo) VALUES ('4278ea09-e3ba-595e-81ff-dbf952a35ed0', 'glass-garden', '유리정원', '식물과 빛, 작은 탐험을 좋아하는 가상 창작자입니다. 한 세계관에서 소설과 캐릭터, 장면 아트를 함께 만듭니다.', '자라는 것들 속에서 이야기를 발견해요.', true, true) ON CONFLICT DO NOTHING;
INSERT INTO workspaces (id, owner_id, name) VALUES ('6e1d9d22-a0de-5dd6-8469-6a770baf7176', '4278ea09-e3ba-595e-81ff-dbf952a35ed0', '유리정원의 목업 작업실') ON CONFLICT DO NOTHING;
INSERT INTO assets (id, workspace_id, storage_key, mime_type, width, height, source, provenance) VALUES ('4979c20a-739b-5545-8d47-3d50edf55739', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'showcase/glass-forest.png', 'image/png', 1536, 1024, 'demo', '{"generatedWith":"image_gen","fictional":true}') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, role) VALUES ('65c386d3-e375-5e81-8fe8-c07818364b44', 'demo.blue-hour', 'demo') ON CONFLICT DO NOTHING;
INSERT INTO creator_profiles (user_id, handle, display_name, bio, tagline, is_public, is_demo) VALUES ('65c386d3-e375-5e81-8fe8-c07818364b44', 'blue-hour', '블루아워', '가까운 미래의 도시와 사람의 기억을 다루는 가상 창작자입니다. 시네마틱 장면을 출발점으로 이야기를 확장합니다.', '현실과 SF 사이의 한 장면.', true, true) ON CONFLICT DO NOTHING;
INSERT INTO workspaces (id, owner_id, name) VALUES ('3874cfbe-373c-50b7-8415-fbdb0791bf6e', '65c386d3-e375-5e81-8fe8-c07818364b44', '블루아워의 목업 작업실') ON CONFLICT DO NOTHING;
INSERT INTO assets (id, workspace_id, storage_key, mime_type, width, height, source, provenance) VALUES ('e95dae11-d3f2-5462-8d0b-97a4d47abaf8', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', 'showcase/rain-city.png', 'image/png', 1536, 1024, 'demo', '{"generatedWith":"image_gen","fictional":true}') ON CONFLICT DO NOTHING;
INSERT INTO projects (id, workspace_id, title, format, stage) VALUES ('3498573b-7ac0-512f-8d1d-e9d51f8970a4', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '월광우체국', 'novel', 'review') ON CONFLICT DO NOTHING;
INSERT INTO stories (id, workspace_id, project_id, premise, planned_episodes) VALUES ('bde10797-1511-5f1e-836e-1dec6cede7e8', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '3498573b-7ac0-512f-8d1d-e9d51f8970a4', '수신인이 잊은 기억을 배달하는 우체국. 마지막 편지에는 배달부 자신의 이름이 적혀 있었다.', 2) ON CONFLICT DO NOTHING;
INSERT INTO episodes (id, workspace_id, story_id, number, title, body, status) VALUES ('8f2230f6-192e-5b86-8883-5313567cb787', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 'bde10797-1511-5f1e-836e-1dec6cede7e8', 1, '수신인 없는 편지', '우체국의 시계는 달이 뜨면 거꾸로 돌았다. 서린은 아무도 묻지 않는 그 규칙을 지키며 서른 번째 밤의 배달 가방을 열었다. 오늘 들어온 편지는 단 한 통. 봉투에는 주소도 이름도 없었지만, 손바닥에 올리자 오래된 바다 냄새가 났다.

‘잊어버린 곳으로 가면 돼.’ 국장은 늘 그렇게 말했다. 서린은 언덕 끝의 파란 대문을 떠올렸다. 그곳에는 집이 없었다. 재작년 화재 이후로 텅 빈 터만 남아 있었다. 그런데도 편지는 그쪽으로 가라고, 가방 안에서 희미하게 빛났다.

지붕을 건너던 서린은 처음 보는 발자국을 발견했다. 눈도 내리지 않은 기와 위에 하얀 자국이 이어졌다. 파란 대문 앞에서 자국이 끊겼다. 문틈으로 어린 목소리가 들렸다.

‘오늘은 엄마가 기억했나요?’

서린이 봉투를 뒤집었다. 빈 종이라고 생각한 뒷면에 글씨가 떠올랐다. 배달하지 말 것. 보낸 사람의 이름은 분명 서린이었다.', 'ready') ON CONFLICT DO NOTHING;
INSERT INTO episode_revisions (episode_id, workspace_id, story_id, version, body, plot) VALUES ('8f2230f6-192e-5b86-8883-5313567cb787', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 'bde10797-1511-5f1e-836e-1dec6cede7e8', 1, '우체국의 시계는 달이 뜨면 거꾸로 돌았다. 서린은 아무도 묻지 않는 그 규칙을 지키며 서른 번째 밤의 배달 가방을 열었다. 오늘 들어온 편지는 단 한 통. 봉투에는 주소도 이름도 없었지만, 손바닥에 올리자 오래된 바다 냄새가 났다.

‘잊어버린 곳으로 가면 돼.’ 국장은 늘 그렇게 말했다. 서린은 언덕 끝의 파란 대문을 떠올렸다. 그곳에는 집이 없었다. 재작년 화재 이후로 텅 빈 터만 남아 있었다. 그런데도 편지는 그쪽으로 가라고, 가방 안에서 희미하게 빛났다.

지붕을 건너던 서린은 처음 보는 발자국을 발견했다. 눈도 내리지 않은 기와 위에 하얀 자국이 이어졌다. 파란 대문 앞에서 자국이 끊겼다. 문틈으로 어린 목소리가 들렸다.

‘오늘은 엄마가 기억했나요?’

서린이 봉투를 뒤집었다. 빈 종이라고 생각한 뒷면에 글씨가 떠올랐다. 배달하지 말 것. 보낸 사람의 이름은 분명 서린이었다.', '') ON CONFLICT DO NOTHING;
INSERT INTO episodes (id, workspace_id, story_id, number, title, body, status) VALUES ('57698380-cd90-5e1e-8236-ef76255d8f42', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 'bde10797-1511-5f1e-836e-1dec6cede7e8', 2, '파란 대문의 약속', '서린은 편지를 뜯지 않은 채 문 앞에 앉았다. 아이는 대문 너머에서 돌멩이를 굴렸다. 하나, 둘, 셋. 소리는 매번 네 번째가 되기 전에 멎었다.

‘네가 여기 산 지 얼마나 됐니?’

‘누나가 편지를 가져오겠다고 한 날부터요.’

가방 안쪽에는 작은 주머니가 있었다. 서린이 한 번도 열어보지 못한 주머니. 봉투를 가까이 대자 잠금쇠가 조용히 풀렸고, 푸른 유리 단추 하나가 손바닥으로 떨어졌다. 바다 냄새는 편지가 아니라 그 단추에서 났다.

서린은 기억했다. 불이 나던 밤, 대문 안에는 아이가 없었다. 자신이 누군가를 기다리고 있었다. 엄마의 코트에서 뜯어진 단추를 쥔 채로.

‘편지를 받으면 이 집은 없어져요.’ 아이가 말했다. ‘그래도 배달할 거예요?’

서린은 봉투에 적힌 자신의 이름을 오래 바라보았다. 배달하지 말 것. 그것은 명령이 아니라, 아직 작별할 준비가 되지 않은 누군가의 부탁이었다.', 'ready') ON CONFLICT DO NOTHING;
INSERT INTO episode_revisions (episode_id, workspace_id, story_id, version, body, plot) VALUES ('57698380-cd90-5e1e-8236-ef76255d8f42', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 'bde10797-1511-5f1e-836e-1dec6cede7e8', 1, '서린은 편지를 뜯지 않은 채 문 앞에 앉았다. 아이는 대문 너머에서 돌멩이를 굴렸다. 하나, 둘, 셋. 소리는 매번 네 번째가 되기 전에 멎었다.

‘네가 여기 산 지 얼마나 됐니?’

‘누나가 편지를 가져오겠다고 한 날부터요.’

가방 안쪽에는 작은 주머니가 있었다. 서린이 한 번도 열어보지 못한 주머니. 봉투를 가까이 대자 잠금쇠가 조용히 풀렸고, 푸른 유리 단추 하나가 손바닥으로 떨어졌다. 바다 냄새는 편지가 아니라 그 단추에서 났다.

서린은 기억했다. 불이 나던 밤, 대문 안에는 아이가 없었다. 자신이 누군가를 기다리고 있었다. 엄마의 코트에서 뜯어진 단추를 쥔 채로.

‘편지를 받으면 이 집은 없어져요.’ 아이가 말했다. ‘그래도 배달할 거예요?’

서린은 봉투에 적힌 자신의 이름을 오래 바라보았다. 배달하지 말 것. 그것은 명령이 아니라, 아직 작별할 준비가 되지 않은 누군가의 부탁이었다.', '') ON CONFLICT DO NOTHING;
INSERT INTO characters (id, workspace_id, name, description, attributes) VALUES ('2c5577b3-565b-5890-8251-0939f3727387', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '서린 · 달빛 배달부', '잊힌 기억의 주소를 읽는 배달부. 누구에게나 편지를 전하지만 자신의 과거만은 읽지 못한다.', '[{"label":"역할","value":"월광우체국의 야간 배달부"},{"label":"인상과 성격","value":"차분하고 관찰력이 좋지만 작별 인사에는 서툴다."},{"label":"외형","value":"짧은 은발, 남색 코트, 아이보리 머플러와 황동 장식 가방"},{"label":"이야기의 단서","value":"푸른 유리 단추, 수신인이 없는 마지막 편지"}]') ON CONFLICT DO NOTHING;
INSERT INTO character_sheets (id, workspace_id, character_id, asset_id) VALUES ('be27d27a-335f-5d3c-858c-47b7f83a04f0', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '2c5577b3-565b-5890-8251-0939f3727387', '806f50da-26c4-5895-862a-cae69df1e772') ON CONFLICT DO NOTHING;
INSERT INTO projects (id, workspace_id, title, format, stage) VALUES ('fd5be2b5-2950-5a77-87d3-5f6cb97069fe', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', '유리숲의 기록', 'novel', 'review') ON CONFLICT DO NOTHING;
INSERT INTO stories (id, workspace_id, project_id, premise, planned_episodes) VALUES ('bd8d1b47-b04e-55be-88c0-84903a5a90e9', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'fd5be2b5-2950-5a77-87d3-5f6cb97069fe', '사라진 사람의 목소리로 자라는 숲. 기록자 아린은 절대로 피어서는 안 되는 씨앗을 발견한다.', 2) ON CONFLICT DO NOTHING;
INSERT INTO episodes (id, workspace_id, story_id, number, title, body, status) VALUES ('44e9b597-31a9-59dd-8a75-406494bbf59e', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'bd8d1b47-b04e-55be-88c0-84903a5a90e9', 1, '아직 이름 없는 잎', '아린의 일은 숲이 말한 것을 적는 일이었다. 보통의 나무는 바람을 빌려 말했지만, 유리숲의 잎은 빛이 닿을 때만 소리를 냈다. 그래서 아린은 해가 뜨기 전에 온실의 창을 모두 닦았다.

그날 아침, 북쪽 선반의 빈 화분에서 잎 하나가 자랐다. 투명하지 않았다. 밤처럼 짙고, 만지면 온기가 느껴졌다. 아린은 표본 노트에 처음으로 ‘분류할 수 없음’이라고 썼다.

‘그건 적으면 안 돼요.’

목소리는 화분 뒤에서 들렸다. 작은 씨앗이 공중에 떠 있었다. 아린은 펜을 멈췄다. 숲의 법칙은 간단했다. 이름을 기록하면 식물은 그 이름대로 자란다. 하지만 이름을 적지 않으면, 누구도 그 식물이 있었다는 사실을 기억하지 못한다.

아린은 노트의 빈칸을 손으로 가렸다. 씨앗이 떨리는 빛을 내며 말했다. ‘내 이름을 알면, 당신도 나를 잃게 될 거예요.’', 'ready') ON CONFLICT DO NOTHING;
INSERT INTO episode_revisions (episode_id, workspace_id, story_id, version, body, plot) VALUES ('44e9b597-31a9-59dd-8a75-406494bbf59e', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'bd8d1b47-b04e-55be-88c0-84903a5a90e9', 1, '아린의 일은 숲이 말한 것을 적는 일이었다. 보통의 나무는 바람을 빌려 말했지만, 유리숲의 잎은 빛이 닿을 때만 소리를 냈다. 그래서 아린은 해가 뜨기 전에 온실의 창을 모두 닦았다.

그날 아침, 북쪽 선반의 빈 화분에서 잎 하나가 자랐다. 투명하지 않았다. 밤처럼 짙고, 만지면 온기가 느껴졌다. 아린은 표본 노트에 처음으로 ‘분류할 수 없음’이라고 썼다.

‘그건 적으면 안 돼요.’

목소리는 화분 뒤에서 들렸다. 작은 씨앗이 공중에 떠 있었다. 아린은 펜을 멈췄다. 숲의 법칙은 간단했다. 이름을 기록하면 식물은 그 이름대로 자란다. 하지만 이름을 적지 않으면, 누구도 그 식물이 있었다는 사실을 기억하지 못한다.

아린은 노트의 빈칸을 손으로 가렸다. 씨앗이 떨리는 빛을 내며 말했다. ‘내 이름을 알면, 당신도 나를 잃게 될 거예요.’', '') ON CONFLICT DO NOTHING;
INSERT INTO episodes (id, workspace_id, story_id, number, title, body, status) VALUES ('099c4763-07e8-50b1-897f-57b02a4a78a3', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'bd8d1b47-b04e-55be-88c0-84903a5a90e9', 2, '기억하는 정원', '다음 날 북쪽 선반은 비어 있었다. 아린은 거기에 무엇이 있었는지 떠올릴 수 없었지만, 노트의 한 페이지가 유난히 따뜻했다. 손바닥 아래에는 아무 글자도 없었다.

그녀는 기록 대신 그림을 그리기로 했다. 짙은 잎, 둥근 화분, 빛나는 작은 점. 세 번째 선을 긋는 순간 숲 전체가 맑은 종소리를 냈다. 잎들이 한꺼번에 아침빛을 되돌려 보내고 있었다.

온실 문턱에 낯선 신발 한 켤레가 놓여 있었다. 신발의 주인은 보이지 않았다. 아린이 빈 의자를 향해 물었다. ‘내가 당신을 잊은 건가요?’

의자 위에 씨앗이 내려앉았다. 이번에는 대답 대신 노트의 끝장을 펼쳤다. 마지막 페이지에는 어린 아린의 그림이 있었다. 두 사람이 같은 화분을 들고 있는 그림.

이름을 기록하면 잃게 된다는 말은 반만 맞았다. 이름으로만 기억하면, 다른 모든 것을 잊는 것이었다. 아린은 펜을 내려놓고 빈 의자 곁에 앉았다.', 'ready') ON CONFLICT DO NOTHING;
INSERT INTO episode_revisions (episode_id, workspace_id, story_id, version, body, plot) VALUES ('099c4763-07e8-50b1-897f-57b02a4a78a3', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'bd8d1b47-b04e-55be-88c0-84903a5a90e9', 1, '다음 날 북쪽 선반은 비어 있었다. 아린은 거기에 무엇이 있었는지 떠올릴 수 없었지만, 노트의 한 페이지가 유난히 따뜻했다. 손바닥 아래에는 아무 글자도 없었다.

그녀는 기록 대신 그림을 그리기로 했다. 짙은 잎, 둥근 화분, 빛나는 작은 점. 세 번째 선을 긋는 순간 숲 전체가 맑은 종소리를 냈다. 잎들이 한꺼번에 아침빛을 되돌려 보내고 있었다.

온실 문턱에 낯선 신발 한 켤레가 놓여 있었다. 신발의 주인은 보이지 않았다. 아린이 빈 의자를 향해 물었다. ‘내가 당신을 잊은 건가요?’

의자 위에 씨앗이 내려앉았다. 이번에는 대답 대신 노트의 끝장을 펼쳤다. 마지막 페이지에는 어린 아린의 그림이 있었다. 두 사람이 같은 화분을 들고 있는 그림.

이름을 기록하면 잃게 된다는 말은 반만 맞았다. 이름으로만 기억하면, 다른 모든 것을 잊는 것이었다. 아린은 펜을 내려놓고 빈 의자 곁에 앉았다.', '') ON CONFLICT DO NOTHING;
INSERT INTO characters (id, workspace_id, name, description, attributes) VALUES ('71b8435b-4574-56d9-8e94-6f2e917caae7', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', '아린 · 숲의 기록자', '식물의 목소리를 기록하는 온실지기. 모든 것에 이름을 붙이던 사람이 이름 없는 씨앗을 만난다.', '[{"label":"역할","value":"유리숲 온실의 식물 기록자"},{"label":"인상과 성격","value":"다정하고 꼼꼼하다. 아직 설명할 수 없는 것을 쉽게 포기하지 않는다."},{"label":"외형","value":"땋은 갈색 머리, 둥근 황동 안경, 크림색 재킷과 올리브색 가방"},{"label":"이야기의 단서","value":"따뜻한 빈 페이지와 공중에 떠 있는 씨앗"}]') ON CONFLICT DO NOTHING;
INSERT INTO character_sheets (id, workspace_id, character_id, asset_id) VALUES ('f15c8261-a29d-58e3-89a3-ebf76a054fad', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', '71b8435b-4574-56d9-8e94-6f2e917caae7', '4979c20a-739b-5545-8d47-3d50edf55739') ON CONFLICT DO NOTHING;
INSERT INTO projects (id, workspace_id, title, format, stage) VALUES ('55c59ea0-08cb-53d2-8a16-ef11b1fc3e70', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '비가 멈춘 도시', 'novel', 'review') ON CONFLICT DO NOTHING;
INSERT INTO stories (id, workspace_id, project_id, premise, planned_episodes) VALUES ('342e0351-0f66-51f5-894f-5d2071f7a623', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '55c59ea0-08cb-53d2-8a16-ef11b1fc3e70', '도시의 비가 멎은 날, 사람들은 어제의 기억을 잃었다. 기억 수리공 도윤에게 도착한 것은 내일의 녹음이었다.', 2) ON CONFLICT DO NOTHING;
INSERT INTO episodes (id, workspace_id, story_id, number, title, body, status) VALUES ('f6f778dd-cd20-5fa3-8443-4138e50fe925', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '342e0351-0f66-51f5-894f-5d2071f7a623', 1, '내일에서 온 녹음', '빗방울이 허공에 멈춘 것은 오후 여섯 시 십칠 분이었다. 도윤은 수리점 밖으로 손을 내밀었다. 방울 하나가 손끝에 닿았지만 물로 흩어지지 않았다. 투명한 작은 유리구슬처럼 차가웠다.

그 시각 도시의 모든 사람은 어제를 잊었다. 도윤만 예외였다. 그의 책상 위에서 오래된 카세트가 돌아가고 있었기 때문이다. 자기테이프는 도시의 기억망에 연결되지 않았다.

테이프 속 목소리는 도윤과 똑같았다. ‘내일 아침, 노란 재킷을 입은 사람을 믿지 마.’

도윤은 자신의 소매를 내려다보았다. 세탁을 미룬 노란 작업복. 누가 장난을 친다고 생각하려던 순간, 녹음이 이어졌다.

‘그리고 수리점 문을 열어 줘. 밖에서 기다리고 있잖아.’

문밖의 남자가 고개를 들었다. 유리에 비친 도윤의 얼굴이, 유리 바깥에서 먼저 웃었다.', 'ready') ON CONFLICT DO NOTHING;
INSERT INTO episode_revisions (episode_id, workspace_id, story_id, version, body, plot) VALUES ('f6f778dd-cd20-5fa3-8443-4138e50fe925', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '342e0351-0f66-51f5-894f-5d2071f7a623', 1, '빗방울이 허공에 멈춘 것은 오후 여섯 시 십칠 분이었다. 도윤은 수리점 밖으로 손을 내밀었다. 방울 하나가 손끝에 닿았지만 물로 흩어지지 않았다. 투명한 작은 유리구슬처럼 차가웠다.

그 시각 도시의 모든 사람은 어제를 잊었다. 도윤만 예외였다. 그의 책상 위에서 오래된 카세트가 돌아가고 있었기 때문이다. 자기테이프는 도시의 기억망에 연결되지 않았다.

테이프 속 목소리는 도윤과 똑같았다. ‘내일 아침, 노란 재킷을 입은 사람을 믿지 마.’

도윤은 자신의 소매를 내려다보았다. 세탁을 미룬 노란 작업복. 누가 장난을 친다고 생각하려던 순간, 녹음이 이어졌다.

‘그리고 수리점 문을 열어 줘. 밖에서 기다리고 있잖아.’

문밖의 남자가 고개를 들었다. 유리에 비친 도윤의 얼굴이, 유리 바깥에서 먼저 웃었다.', '') ON CONFLICT DO NOTHING;
INSERT INTO episodes (id, workspace_id, story_id, number, title, body, status) VALUES ('14ca0ca9-d198-57a1-8375-99ce55bb1217', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '342e0351-0f66-51f5-894f-5d2071f7a623', 2, '어제의 손님', '도윤은 문을 열지 않았다. 대신 테이프를 뒤로 감았다. 잡음 속에서 창문을 두드리는 소리가 들렸다. 세 번, 잠깐 쉬고 두 번. 밖의 남자가 정확히 같은 박자로 유리를 두드렸다.

‘당신은 내일의 나인가?’ 도윤이 물었다.

남자는 고개를 저었다. ‘네가 어제 지운 기억이야.’

수리점의 장부에는 자신의 필체로 쓴 의뢰가 남아 있었다. 의뢰인: 도윤. 작업 내용: 도시를 멈추는 방법을 잊게 할 것. 잔금은 공란이었다.

도윤은 기억망에 연결하지 않는다고 믿었던 카세트의 뒷면을 열었다. 배터리 자리에는 작은 빗방울이 들어 있었다. 처음 손끝에서 느낀 것과 같은 온도였다.

남자가 다시 말했다. ‘아직 잔금을 안 냈어. 기억 하나로는 도시 전체를 멈출 수 없거든.’

공중에 멎어 있던 비가 아주 조금 아래로 움직였다. 도윤은 그제야 깨달았다. 테이프는 미래를 녹음한 것이 아니었다. 도시가 빌려준 시간을 되감고 있었다.', 'ready') ON CONFLICT DO NOTHING;
INSERT INTO episode_revisions (episode_id, workspace_id, story_id, version, body, plot) VALUES ('14ca0ca9-d198-57a1-8375-99ce55bb1217', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '342e0351-0f66-51f5-894f-5d2071f7a623', 1, '도윤은 문을 열지 않았다. 대신 테이프를 뒤로 감았다. 잡음 속에서 창문을 두드리는 소리가 들렸다. 세 번, 잠깐 쉬고 두 번. 밖의 남자가 정확히 같은 박자로 유리를 두드렸다.

‘당신은 내일의 나인가?’ 도윤이 물었다.

남자는 고개를 저었다. ‘네가 어제 지운 기억이야.’

수리점의 장부에는 자신의 필체로 쓴 의뢰가 남아 있었다. 의뢰인: 도윤. 작업 내용: 도시를 멈추는 방법을 잊게 할 것. 잔금은 공란이었다.

도윤은 기억망에 연결하지 않는다고 믿었던 카세트의 뒷면을 열었다. 배터리 자리에는 작은 빗방울이 들어 있었다. 처음 손끝에서 느낀 것과 같은 온도였다.

남자가 다시 말했다. ‘아직 잔금을 안 냈어. 기억 하나로는 도시 전체를 멈출 수 없거든.’

공중에 멎어 있던 비가 아주 조금 아래로 움직였다. 도윤은 그제야 깨달았다. 테이프는 미래를 녹음한 것이 아니었다. 도시가 빌려준 시간을 되감고 있었다.', '') ON CONFLICT DO NOTHING;
INSERT INTO characters (id, workspace_id, name, description, attributes) VALUES ('481ce421-8e32-5232-8d0f-52a35bad66e4', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '도윤 · 기억 수리공', '낡은 기억 장치를 수리하는 기술자. 모두가 잊은 어제를 기억하지만, 자신이 지운 선택은 모른다.', '[{"label":"역할","value":"기억 카세트를 수리하는 기술자"},{"label":"인상과 성격","value":"말수는 적지만 고장 난 것을 그냥 지나치지 못한다."},{"label":"외형","value":"검은 머리, 노란 기능성 재킷, 오래된 투명 카세트"},{"label":"이야기의 단서","value":"미래의 목소리와 지불되지 않은 수리비"}]') ON CONFLICT DO NOTHING;
INSERT INTO character_sheets (id, workspace_id, character_id, asset_id) VALUES ('d8258e84-b435-50bc-85ea-063af5ce3ef3', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '481ce421-8e32-5232-8d0f-52a35bad66e4', 'e95dae11-d3f2-5462-8d0b-97a4d47abaf8') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('88123413-d39e-54f7-825c-63c27e2ddcaf', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '954cca66-f6db-5aaa-8ec1-c86d875a031c', 'moon-post-office', 'novel', '월광우체국', '수신인이 잊은 기억을 배달하는 우체국. 마지막 편지에는 배달부 자신의 이름이 적혀 있었다.', '{"판타지","미스터리","연재 소설"}', '/showcase/moon-post.png', '달빛 아래 지붕 위에서 빛나는 편지를 든 은발의 우편배달부', '', '[]', 'public', 'published', '2026-10-08T00:00:00Z', true, '3498573b-7ac0-512f-8d1d-e9d51f8970a4', NULL) ON CONFLICT DO NOTHING;
INSERT INTO publication_chapters (publication_id, workspace_id, number, title, body) VALUES ('88123413-d39e-54f7-825c-63c27e2ddcaf', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 1, '수신인 없는 편지', '우체국의 시계는 달이 뜨면 거꾸로 돌았다. 서린은 아무도 묻지 않는 그 규칙을 지키며 서른 번째 밤의 배달 가방을 열었다. 오늘 들어온 편지는 단 한 통. 봉투에는 주소도 이름도 없었지만, 손바닥에 올리자 오래된 바다 냄새가 났다.

‘잊어버린 곳으로 가면 돼.’ 국장은 늘 그렇게 말했다. 서린은 언덕 끝의 파란 대문을 떠올렸다. 그곳에는 집이 없었다. 재작년 화재 이후로 텅 빈 터만 남아 있었다. 그런데도 편지는 그쪽으로 가라고, 가방 안에서 희미하게 빛났다.

지붕을 건너던 서린은 처음 보는 발자국을 발견했다. 눈도 내리지 않은 기와 위에 하얀 자국이 이어졌다. 파란 대문 앞에서 자국이 끊겼다. 문틈으로 어린 목소리가 들렸다.

‘오늘은 엄마가 기억했나요?’

서린이 봉투를 뒤집었다. 빈 종이라고 생각한 뒷면에 글씨가 떠올랐다. 배달하지 말 것. 보낸 사람의 이름은 분명 서린이었다.') ON CONFLICT DO NOTHING;
INSERT INTO publication_chapters (publication_id, workspace_id, number, title, body) VALUES ('88123413-d39e-54f7-825c-63c27e2ddcaf', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', 2, '파란 대문의 약속', '서린은 편지를 뜯지 않은 채 문 앞에 앉았다. 아이는 대문 너머에서 돌멩이를 굴렸다. 하나, 둘, 셋. 소리는 매번 네 번째가 되기 전에 멎었다.

‘네가 여기 산 지 얼마나 됐니?’

‘누나가 편지를 가져오겠다고 한 날부터요.’

가방 안쪽에는 작은 주머니가 있었다. 서린이 한 번도 열어보지 못한 주머니. 봉투를 가까이 대자 잠금쇠가 조용히 풀렸고, 푸른 유리 단추 하나가 손바닥으로 떨어졌다. 바다 냄새는 편지가 아니라 그 단추에서 났다.

서린은 기억했다. 불이 나던 밤, 대문 안에는 아이가 없었다. 자신이 누군가를 기다리고 있었다. 엄마의 코트에서 뜯어진 단추를 쥔 채로.

‘편지를 받으면 이 집은 없어져요.’ 아이가 말했다. ‘그래도 배달할 거예요?’

서린은 봉투에 적힌 자신의 이름을 오래 바라보았다. 배달하지 말 것. 그것은 명령이 아니라, 아직 작별할 준비가 되지 않은 누군가의 부탁이었다.') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('ea3d7d83-3de7-5aff-8bd0-4d6765cd0dee', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '954cca66-f6db-5aaa-8ec1-c86d875a031c', 'character-seorin', 'character', '서린 · 달빛 배달부', '잊힌 기억의 주소를 읽는 배달부. 누구에게나 편지를 전하지만 자신의 과거만은 읽지 못한다.', '{"캐릭터","판타지","은발"}', '/showcase/moon-post.png', '짧은 은발과 아이보리 머플러, 남색 코트를 입은 서린', '', '[{"label":"역할","value":"월광우체국의 야간 배달부"},{"label":"인상과 성격","value":"차분하고 관찰력이 좋지만 작별 인사에는 서툴다."},{"label":"외형","value":"짧은 은발, 남색 코트, 아이보리 머플러와 황동 장식 가방"},{"label":"이야기의 단서","value":"푸른 유리 단추, 수신인이 없는 마지막 편지"}]', 'public', 'published', '2026-10-07T08:00:00Z', true, NULL, '2c5577b3-565b-5890-8251-0939f3727387') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('02fca065-f0bd-55cf-85fb-6dfc534b8193', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '954cca66-f6db-5aaa-8ec1-c86d875a031c', 'moon-rooftop', 'content', '달빛 아래 첫 번째 배달', '월광우체국 1화를 장면으로 옮긴 콘셉트 아트. 차가운 달빛과 따뜻한 집의 불빛을 대비했습니다.', '{"장면 아트","애니메이션","콘셉트"}', '/showcase/moon-post.png', '달과 따뜻한 창문 불빛이 어우러진 언덕 도시의 콘셉트 아트', '지붕의 대각선이 멀리 있는 파란 대문으로 시선을 이끕니다. 서린의 코트와 도시의 푸른 밤을 같은 계열로 두고, 배달할 편지와 창문에만 따뜻한 빛을 남겼습니다.

영상화할 때는 도시의 전경에서 편지로 천천히 가까워지는 첫 컷을 상정했습니다. 현재 콘텐츠는 AI로 생성한 정지 이미지 목업이며, 재생 가능한 영상은 포함하지 않습니다.', '[]', 'public', 'published', '2026-10-08T01:00:00Z', true, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('833cdf83-1ec1-5339-8cef-e2b077859a00', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', '4278ea09-e3ba-595e-81ff-dbf952a35ed0', 'glass-forest-records', 'novel', '유리숲의 기록', '사라진 사람의 목소리로 자라는 숲. 기록자 아린은 절대로 피어서는 안 되는 씨앗을 발견한다.', '{"힐링 판타지","탐험","연재 소설"}', '/showcase/glass-forest.png', '유리 잎이 자라는 온실에서 표본 노트를 펼친 식물 기록자', '', '[]', 'public', 'published', '2026-10-07T01:00:00Z', true, 'fd5be2b5-2950-5a77-87d3-5f6cb97069fe', NULL) ON CONFLICT DO NOTHING;
INSERT INTO publication_chapters (publication_id, workspace_id, number, title, body) VALUES ('833cdf83-1ec1-5339-8cef-e2b077859a00', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 1, '아직 이름 없는 잎', '아린의 일은 숲이 말한 것을 적는 일이었다. 보통의 나무는 바람을 빌려 말했지만, 유리숲의 잎은 빛이 닿을 때만 소리를 냈다. 그래서 아린은 해가 뜨기 전에 온실의 창을 모두 닦았다.

그날 아침, 북쪽 선반의 빈 화분에서 잎 하나가 자랐다. 투명하지 않았다. 밤처럼 짙고, 만지면 온기가 느껴졌다. 아린은 표본 노트에 처음으로 ‘분류할 수 없음’이라고 썼다.

‘그건 적으면 안 돼요.’

목소리는 화분 뒤에서 들렸다. 작은 씨앗이 공중에 떠 있었다. 아린은 펜을 멈췄다. 숲의 법칙은 간단했다. 이름을 기록하면 식물은 그 이름대로 자란다. 하지만 이름을 적지 않으면, 누구도 그 식물이 있었다는 사실을 기억하지 못한다.

아린은 노트의 빈칸을 손으로 가렸다. 씨앗이 떨리는 빛을 내며 말했다. ‘내 이름을 알면, 당신도 나를 잃게 될 거예요.’') ON CONFLICT DO NOTHING;
INSERT INTO publication_chapters (publication_id, workspace_id, number, title, body) VALUES ('833cdf83-1ec1-5339-8cef-e2b077859a00', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', 2, '기억하는 정원', '다음 날 북쪽 선반은 비어 있었다. 아린은 거기에 무엇이 있었는지 떠올릴 수 없었지만, 노트의 한 페이지가 유난히 따뜻했다. 손바닥 아래에는 아무 글자도 없었다.

그녀는 기록 대신 그림을 그리기로 했다. 짙은 잎, 둥근 화분, 빛나는 작은 점. 세 번째 선을 긋는 순간 숲 전체가 맑은 종소리를 냈다. 잎들이 한꺼번에 아침빛을 되돌려 보내고 있었다.

온실 문턱에 낯선 신발 한 켤레가 놓여 있었다. 신발의 주인은 보이지 않았다. 아린이 빈 의자를 향해 물었다. ‘내가 당신을 잊은 건가요?’

의자 위에 씨앗이 내려앉았다. 이번에는 대답 대신 노트의 끝장을 펼쳤다. 마지막 페이지에는 어린 아린의 그림이 있었다. 두 사람이 같은 화분을 들고 있는 그림.

이름을 기록하면 잃게 된다는 말은 반만 맞았다. 이름으로만 기억하면, 다른 모든 것을 잊는 것이었다. 아린은 펜을 내려놓고 빈 의자 곁에 앉았다.') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('0c2375d3-bbea-5cfe-8911-06f34dc974c6', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', '4278ea09-e3ba-595e-81ff-dbf952a35ed0', 'character-arin', 'character', '아린 · 숲의 기록자', '식물의 목소리를 기록하는 온실지기. 모든 것에 이름을 붙이던 사람이 이름 없는 씨앗을 만난다.', '{"캐릭터","식물","탐험가"}', '/showcase/glass-forest.png', '땋은 갈색 머리와 둥근 안경, 크림색 재킷을 입은 아린', '', '[{"label":"역할","value":"유리숲 온실의 식물 기록자"},{"label":"인상과 성격","value":"다정하고 꼼꼼하다. 아직 설명할 수 없는 것을 쉽게 포기하지 않는다."},{"label":"외형","value":"땋은 갈색 머리, 둥근 황동 안경, 크림색 재킷과 올리브색 가방"},{"label":"이야기의 단서","value":"따뜻한 빈 페이지와 공중에 떠 있는 씨앗"}]', 'public', 'published', '2026-10-06T04:00:00Z', true, NULL, '71b8435b-4574-56d9-8e94-6f2e917caae7') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('1e48b39a-72cd-5b6a-8d3e-88f3b82bdc68', '6e1d9d22-a0de-5dd6-8469-6a770baf7176', '4278ea09-e3ba-595e-81ff-dbf952a35ed0', 'glass-seed', 'content', '빛이 자라는 온실', '투명한 잎과 아침빛으로 만든 유리숲의 첫 장면. 식물과 기억의 경계를 표현한 이미지 콘텐츠입니다.', '{"이미지","판타지","아트워크"}', '/showcase/glass-forest.png', '황금빛 아침 햇살을 통과시키는 투명한 잎과 떠다니는 씨앗', '유리처럼 투명한 잎을 차갑게 보이게 하지 않는 것이 이 장면의 목표였습니다. 크림색 의상과 아침의 금빛을 중심으로, 가장 어두운 부분에도 초록을 남겼습니다.

아린이 노트에서 시선을 드는 순간을 담았습니다. 이야기에 등장하는 씨앗은 작게 떠다니는 빛으로 표현했습니다. 이 이미지는 공개 탐색 화면을 위한 AI 생성 목업입니다.', '[]', 'public', 'published', '2026-10-07T05:00:00Z', true, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('2fee440e-e474-532f-822d-e58bbbca275f', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '65c386d3-e375-5e81-8fe8-c07818364b44', 'city-without-rain', 'novel', '비가 멈춘 도시', '도시의 비가 멎은 날, 사람들은 어제의 기억을 잃었다. 기억 수리공 도윤에게 도착한 것은 내일의 녹음이었다.', '{"SF","도시 미스터리","연재 소설"}', '/showcase/rain-city.png', '공중에 멈춘 빗방울 사이에서 기억 카세트를 든 노란 재킷의 남성', '', '[]', 'public', 'published', '2026-10-06T00:00:00Z', true, '55c59ea0-08cb-53d2-8a16-ef11b1fc3e70', NULL) ON CONFLICT DO NOTHING;
INSERT INTO publication_chapters (publication_id, workspace_id, number, title, body) VALUES ('2fee440e-e474-532f-822d-e58bbbca275f', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', 1, '내일에서 온 녹음', '빗방울이 허공에 멈춘 것은 오후 여섯 시 십칠 분이었다. 도윤은 수리점 밖으로 손을 내밀었다. 방울 하나가 손끝에 닿았지만 물로 흩어지지 않았다. 투명한 작은 유리구슬처럼 차가웠다.

그 시각 도시의 모든 사람은 어제를 잊었다. 도윤만 예외였다. 그의 책상 위에서 오래된 카세트가 돌아가고 있었기 때문이다. 자기테이프는 도시의 기억망에 연결되지 않았다.

테이프 속 목소리는 도윤과 똑같았다. ‘내일 아침, 노란 재킷을 입은 사람을 믿지 마.’

도윤은 자신의 소매를 내려다보았다. 세탁을 미룬 노란 작업복. 누가 장난을 친다고 생각하려던 순간, 녹음이 이어졌다.

‘그리고 수리점 문을 열어 줘. 밖에서 기다리고 있잖아.’

문밖의 남자가 고개를 들었다. 유리에 비친 도윤의 얼굴이, 유리 바깥에서 먼저 웃었다.') ON CONFLICT DO NOTHING;
INSERT INTO publication_chapters (publication_id, workspace_id, number, title, body) VALUES ('2fee440e-e474-532f-822d-e58bbbca275f', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', 2, '어제의 손님', '도윤은 문을 열지 않았다. 대신 테이프를 뒤로 감았다. 잡음 속에서 창문을 두드리는 소리가 들렸다. 세 번, 잠깐 쉬고 두 번. 밖의 남자가 정확히 같은 박자로 유리를 두드렸다.

‘당신은 내일의 나인가?’ 도윤이 물었다.

남자는 고개를 저었다. ‘네가 어제 지운 기억이야.’

수리점의 장부에는 자신의 필체로 쓴 의뢰가 남아 있었다. 의뢰인: 도윤. 작업 내용: 도시를 멈추는 방법을 잊게 할 것. 잔금은 공란이었다.

도윤은 기억망에 연결하지 않는다고 믿었던 카세트의 뒷면을 열었다. 배터리 자리에는 작은 빗방울이 들어 있었다. 처음 손끝에서 느낀 것과 같은 온도였다.

남자가 다시 말했다. ‘아직 잔금을 안 냈어. 기억 하나로는 도시 전체를 멈출 수 없거든.’

공중에 멎어 있던 비가 아주 조금 아래로 움직였다. 도윤은 그제야 깨달았다. 테이프는 미래를 녹음한 것이 아니었다. 도시가 빌려준 시간을 되감고 있었다.') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('56da6f4f-df3b-5bcc-8255-12b2e74aef82', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '65c386d3-e375-5e81-8fe8-c07818364b44', 'character-doyun', 'character', '도윤 · 기억 수리공', '낡은 기억 장치를 수리하는 기술자. 모두가 잊은 어제를 기억하지만, 자신이 지운 선택은 모른다.', '{"캐릭터","SF","도시"}', '/showcase/rain-city.png', '노란 기능성 재킷을 입고 투명한 카세트를 든 도윤', '', '[{"label":"역할","value":"기억 카세트를 수리하는 기술자"},{"label":"인상과 성격","value":"말수는 적지만 고장 난 것을 그냥 지나치지 못한다."},{"label":"외형","value":"검은 머리, 노란 기능성 재킷, 오래된 투명 카세트"},{"label":"이야기의 단서","value":"미래의 목소리와 지불되지 않은 수리비"}]', 'public', 'published', '2026-10-05T01:00:00Z', true, NULL, '481ce421-8e32-5232-8d0f-52a35bad66e4') ON CONFLICT DO NOTHING;
INSERT INTO publications (id, workspace_id, creator_id, slug, kind, title, summary, tags, cover_public_path, cover_alt, public_body, public_character_details, visibility, status, published_at, is_demo, source_project_id, source_character_id) VALUES ('cf1531ed-5b52-52da-80d5-fc4844909dda', '3874cfbe-373c-50b7-8415-fbdb0791bf6e', '65c386d3-e375-5e81-8fe8-c07818364b44', 'suspended-rain', 'content', '18:17, 정지한 거리', '비가 멈춘 도시의 티저 콘셉트 이미지. 시간을 멈춘 빗방울과 노란 재킷으로 주인공을 드러냅니다.', '{"시네마틱","콘셉트 이미지","SF"}', '/showcase/rain-city.png', '고가철도 아래 푸른 거리와 공중에 정지한 빗방울', '가까운 미래의 도시를 낯설게 만드는 장치는 화려한 기계보다 작은 물리 법칙의 변화입니다. 떨어지지 않는 빗방울을 전경에 두고, 배경의 열차와 사람들은 평소처럼 움직이는 순간을 상상했습니다.

노란 재킷은 푸른 도시 속에서 도윤을 찾게 하는 시각적 기준입니다. 이 게시물은 AI로 생성한 장면 이미지 목업이며, 실제 영상 파일은 제공하지 않습니다.', '[]', 'public', 'published', '2026-10-06T07:00:00Z', true, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('88123413-d39e-54f7-825c-63c27e2ddcaf', 'ea3d7d83-3de7-5aff-8bd0-4d6765cd0dee', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('88123413-d39e-54f7-825c-63c27e2ddcaf', '02fca065-f0bd-55cf-85fb-6dfc534b8193', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380') ON CONFLICT DO NOTHING;
INSERT INTO project_characters (workspace_id, project_id, character_id) VALUES ('c6e23cda-e53f-5ecf-8ac6-3b910d5ad380', '3498573b-7ac0-512f-8d1d-e9d51f8970a4', '2c5577b3-565b-5890-8251-0939f3727387') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('ea3d7d83-3de7-5aff-8bd0-4d6765cd0dee', '88123413-d39e-54f7-825c-63c27e2ddcaf', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('ea3d7d83-3de7-5aff-8bd0-4d6765cd0dee', '02fca065-f0bd-55cf-85fb-6dfc534b8193', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('02fca065-f0bd-55cf-85fb-6dfc534b8193', '88123413-d39e-54f7-825c-63c27e2ddcaf', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('02fca065-f0bd-55cf-85fb-6dfc534b8193', 'ea3d7d83-3de7-5aff-8bd0-4d6765cd0dee', 'c6e23cda-e53f-5ecf-8ac6-3b910d5ad380') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('833cdf83-1ec1-5339-8cef-e2b077859a00', '0c2375d3-bbea-5cfe-8911-06f34dc974c6', '6e1d9d22-a0de-5dd6-8469-6a770baf7176') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('833cdf83-1ec1-5339-8cef-e2b077859a00', '1e48b39a-72cd-5b6a-8d3e-88f3b82bdc68', '6e1d9d22-a0de-5dd6-8469-6a770baf7176') ON CONFLICT DO NOTHING;
INSERT INTO project_characters (workspace_id, project_id, character_id) VALUES ('6e1d9d22-a0de-5dd6-8469-6a770baf7176', 'fd5be2b5-2950-5a77-87d3-5f6cb97069fe', '71b8435b-4574-56d9-8e94-6f2e917caae7') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('0c2375d3-bbea-5cfe-8911-06f34dc974c6', '833cdf83-1ec1-5339-8cef-e2b077859a00', '6e1d9d22-a0de-5dd6-8469-6a770baf7176') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('0c2375d3-bbea-5cfe-8911-06f34dc974c6', '1e48b39a-72cd-5b6a-8d3e-88f3b82bdc68', '6e1d9d22-a0de-5dd6-8469-6a770baf7176') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('1e48b39a-72cd-5b6a-8d3e-88f3b82bdc68', '833cdf83-1ec1-5339-8cef-e2b077859a00', '6e1d9d22-a0de-5dd6-8469-6a770baf7176') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('1e48b39a-72cd-5b6a-8d3e-88f3b82bdc68', '0c2375d3-bbea-5cfe-8911-06f34dc974c6', '6e1d9d22-a0de-5dd6-8469-6a770baf7176') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('2fee440e-e474-532f-822d-e58bbbca275f', '56da6f4f-df3b-5bcc-8255-12b2e74aef82', '3874cfbe-373c-50b7-8415-fbdb0791bf6e') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('2fee440e-e474-532f-822d-e58bbbca275f', 'cf1531ed-5b52-52da-80d5-fc4844909dda', '3874cfbe-373c-50b7-8415-fbdb0791bf6e') ON CONFLICT DO NOTHING;
INSERT INTO project_characters (workspace_id, project_id, character_id) VALUES ('3874cfbe-373c-50b7-8415-fbdb0791bf6e', '55c59ea0-08cb-53d2-8a16-ef11b1fc3e70', '481ce421-8e32-5232-8d0f-52a35bad66e4') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('56da6f4f-df3b-5bcc-8255-12b2e74aef82', '2fee440e-e474-532f-822d-e58bbbca275f', '3874cfbe-373c-50b7-8415-fbdb0791bf6e') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('56da6f4f-df3b-5bcc-8255-12b2e74aef82', 'cf1531ed-5b52-52da-80d5-fc4844909dda', '3874cfbe-373c-50b7-8415-fbdb0791bf6e') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('cf1531ed-5b52-52da-80d5-fc4844909dda', '2fee440e-e474-532f-822d-e58bbbca275f', '3874cfbe-373c-50b7-8415-fbdb0791bf6e') ON CONFLICT DO NOTHING;
INSERT INTO publication_links (publication_id, related_id, workspace_id) VALUES ('cf1531ed-5b52-52da-80d5-fc4844909dda', '56da6f4f-df3b-5bcc-8255-12b2e74aef82', '3874cfbe-373c-50b7-8415-fbdb0791bf6e') ON CONFLICT DO NOTHING;
INSERT INTO membership_plans (code, name, state, monthly_price_krw, yearly_price_krw, proposed_features) VALUES ('free', 'Free', 'free', 0, 0, '["제작 보드와 트렌드 탐색","캐릭터·시나리오 제작 흐름 살펴보기","이미지·영상과 컷 편집 화면","공개 MCP 연결 안내"]') ON CONFLICT DO NOTHING;
INSERT INTO membership_plans (code, name, state, monthly_price_krw, yearly_price_krw, proposed_features) VALUES ('creator', 'Creator', 'coming_soon', NULL, NULL, '["Free의 기본 제작 흐름","캐릭터 시트·프롬프트 템플릿 확장","회차별 원고와 복선 관리 중심 구성","이미지·영상 생성 이용량 확장 예정","MCP를 통한 대화형 제작"]') ON CONFLICT DO NOTHING;
INSERT INTO membership_plans (code, name, state, monthly_price_krw, yearly_price_krw, proposed_features) VALUES ('pro', 'Pro', 'coming_soon', NULL, NULL, '["Creator의 제작 구성","장편·다회차 프로젝트를 위한 이용량","캐릭터·스타일 템플릿 활용 확대","이미지·영상 생성 이용량 추가 확대 예정","생성 작업 우선 처리 검토 중"]') ON CONFLICT DO NOTHING;
COMMIT;
