'use client';
import { createContext, useContext } from 'react';
import { TrendIcon as I } from './Icons';
import { VIEWS, thumb } from './data';
import { fmt, fmt2, timeAgo } from '../../_lib/trend-helpers';
import { safeUrl } from '../../_lib/integration-api';
export const TrendContext=createContext(null);
export function Bookmark({item}){const {saved,toggleSaved,busy}=useContext(TrendContext),selected=saved.some(s=>s.url===item.url);if(!safeUrl(item.url))return null;return <button type="button" className={'bookmark-btn'+(selected?' saved':'')} aria-label={selected?'저장 해제':'카드 저장'} aria-pressed={selected} disabled={busy===item.url} onClick={e=>{e.stopPropagation();void toggleSaved(item);}} onKeyDown={e=>e.stopPropagation()}><I name="bookmark"/></button>;}
export function ClickCard({item,className,children,...props}){const {open,seen}=useContext(TrendContext),key=item.seenId||item.url||item.id;return <article className={className+(seen.has(key)?' seen':'')} tabIndex={0} role="button" onClick={()=>open(item)} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();open(item);}}} {...props}>{children}</article>;}
export function Meta({items,text=false}){return <>{items.filter(Boolean).map((m,i)=><span key={i} className={m.className||''}>{m.icon?<><I name={m.icon}/>{' '}</>:m.label?m.label+' ':''}{text?<b>{m.value}</b>:<span>{m.value}</span>}</span>)}</>;}
export function MediaCard({item,rank,source,sort}){
 const video=['youtube','shorts'].includes(source),social=['x','threads'].includes(source),url=video?`https://www.youtube.com/watch?v=${item.id}`:item.url;
 const entry={source,id:item.id||url,title:social?item.text:item.title,url,thumbnail:social?item.media:item.thumbnail,...(video?{videoId:item.id,vertical:source==='shorts'}:{})};
 const image=video?item.thumbnail:thumb(entry.thumbnail),subtitle=video?'':`@${item.account}`;
 const meta=video?[{label:'조회수',value:fmt(item.views),className:sort==='views'?'views':''},item.likes?{icon:'thumbs-up',value:fmt2(item.likes),className:'views'}:null,{value:item.channel,className:'chn'},{value:item.published||''}]:social?[{icon:'heart',value:fmt2(item.likes),className:sort==='likes'?'hot':''},{icon:'message',value:fmt2(item.replies),className:sort==='replies'?'hot':''},{icon:'repeat',value:fmt2(source==='threads'?item.reposts:item.retweets),className:sort==='reposts'?'hot':''},item.views?{icon:'eye',value:fmt2(item.views),className:sort==='views'?'hot':''}:null]:[['views','eye'],['likes','heart'],['comments','message']].map(([key,icon])=>({icon,value:fmt2(item[key]),className:sort===key?'views':''}));
 return <ClickCard item={entry} className={'trend-card '+(social?'text postcard':source==='youtube'?'video card':'shorts card')}>{social?<><div className="phead"><span className={'prank'+(rank<=3?' top':'')}>{rank}위</span><span className="pacct">{subtitle}</span></div><div className="ptext">{entry.title}</div>{image&&<img className="pmedia" src={image} loading="lazy" alt=""/>}<Bookmark item={entry}/><div className="sub pstats"><Meta items={meta} text/></div></>:<>{image?<div className="thumb-wrap"><img className="thumb" src={image} loading="lazy" alt=""/><div className={'rank'+(rank<=3?' top':'')}>{rank}위</div><Bookmark item={entry}/>{item.length&&<div className="len">{item.length}</div>}</div>:<Bookmark item={entry}/>}<div className="meta"><div className="title">{entry.title}</div><div className="sub"><Meta items={meta}/></div>{subtitle&&<div className="sub" style={{marginTop:3}}><span>{subtitle}</span></div>}</div></>}</ClickCard>;
}
export function HomeRow({item,rank,section}){return <ClickCard item={item} className="home-row" style={{'--home-color':`var(${section.color})`}}>{item.thumbnail?<img className={'home-row-thumb'+(item.vertical?' vertical':'')} loading="lazy" alt="" src={item.thumbnail}/>:<div className={'home-row-thumb'+(item.vertical?' vertical':'')} aria-hidden="true"/>}<div><div className="home-row-rank">{rank}위</div><div className="home-row-title">{item.title}</div><div className="home-row-meta">{(item.meta||[]).slice(0,4).map((value,i)=><span key={i} className={value===item.hot?'hot':''}>{value}</span>)}</div></div></ClickCard>;}
export function SavedCard({item}){const {toggleSaved,busy}=useContext(TrendContext),meta=VIEWS.find(v=>v.id===item.source)||{label:item.source||'출처',color:'--accent'},image=thumb(item.thumbnail);return <ClickCard item={item} className="saved-card">{image?<img className="saved-thumb" src={image} loading="lazy" alt=""/>:<div className="saved-thumb" aria-hidden="true"/>}<button type="button" className="del" aria-label={`${item.title||'저장한 카드'} 삭제`} disabled={busy===item.url} onClick={e=>{e.stopPropagation();void toggleSaved(item);}} onKeyDown={e=>e.stopPropagation()}>삭제</button><div className="saved-meta"><div className="saved-title">{item.title}</div><div className="saved-sub"><span className="saved-source" style={{'--source-color':`var(${meta.color})`}}>{meta.label}</span><span>{timeAgo(item.savedAt)}</span></div></div></ClickCard>;}
export function AnalysisCard({cluster:c}){const momentum=['rising','stable','falling'].includes(c.momentum)?c.momentum:'stable';return <article className="an-card"><div className="an-card-head"><h2 className="an-title">{c.title}</h2><span className={'an-momentum '+momentum}><I name={{rising:'trend-up',stable:'trend-right',falling:'trend-down'}[momentum]}/>{{rising:'상승',stable:'유지',falling:'하락'}[momentum]}</span></div><div className="an-platforms">{(c.platforms||[]).map(p=><span key={p} className="an-badge" style={{'--an-platform-color':`var(--c-${p.toLowerCase()}, var(--accent))`}}>{p}</span>)}</div>{c.why&&<p className="an-why">{c.why}</p>}<div className="an-keywords">{(c.keywords||[]).slice(0,5).map((k,i)=><span key={i} className="an-keyword">{k}</span>)}</div><div className="an-evidence">{(c.evidence||[]).filter(e=>safeUrl(e.url)).map((e,i)=><a key={i} href={e.url} target="_blank" rel="noopener noreferrer">{e.title||e.url}</a>)}</div></article>;}
export function DateCard({item,rank}){return <ClickCard item={item} className="date-card">{item.thumbnail&&<img className="date-thumb" src={thumb(item.thumbnail)} loading="lazy" alt=""/>}<div className="date-meta"><div className="date-title">{item.title}</div><div className="date-sub">{[`${rank}위`,item.source,item.metric,item.account?`@${item.account}`:'',item.published].filter(Boolean).map((text,i)=><span key={i}>{text}</span>)}{(item.tags||[]).slice(0,3).map((tag,i)=><span className="date-tag" key={'t'+i}>{tag}</span>)}</div></div></ClickCard>;}
