'use client';
import { useEffect, useRef, useState } from 'react';
import { toolApi, safeUrl } from '../../_lib/integration-api';
import { cacheAgeText, feedFailureCount, feedErrorSummary } from '../../_lib/trend-helpers';
import { useStudio } from '../StudioProvider';
import { TrendIcon as I } from './Icons';
import { SORT, thumb } from './data';
export function FeedStatus({data,error,loading}){if(loading)return <div className="status" role="status">불러오는 중…</div>;if(error||['error','blocked'].includes(data?.status))return <div className="error-inline" role="alert"><strong>일시적으로 가져오지 못했습니다</strong><span>{error||feedErrorSummary(data)} · 새로고침을 누르면 다시 시도합니다.</span></div>;return <div className="status cache-age">{cacheAgeText(data)}{data?.status==='partial'&&<span className="cache-age-line">{feedFailureCount(data.errors)}개 계정은 이번 수집에서 실패했습니다.</span>}</div>;}
export function Empty({title='표시할 항목이 없습니다',body='잠시 후 새로고침하거나 국가와 필터를 바꿔 확인해 주세요.'}){return <div className="empty-state"><strong>{title}</strong><span>{body}</span></div>;}
export function SortMenu({value,options,onChange}){const [open,setOpen]=useState(false),ref=useRef();useEffect(()=>{const close=e=>{if(e.type==='keydown'&&e.key!=='Escape')return;if(e.type==='keydown'||!ref.current?.contains(e.target))setOpen(false);};document.addEventListener('click',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',close);};},[]);return <div ref={ref} className={'sortmenu'+(open?' open':'')} data-sort={value}><button className="sorttoggle" type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}>정렬: <span className="curlabel">{SORT[value]?.[0]}</span><span className="caret"><I name="chevron-down"/></span></button><div className="sortlist" role="listbox" aria-label="정렬 방법">{options.map(key=><button key={key} type="button" role="option" aria-selected={key===value} className={key===value?'sel':''} onClick={()=>{onChange(key);setOpen(false);}}><span><I name={SORT[key][1]}/></span><span>{SORT[key][0]}</span><span className="check"><I name="check"/></span></button>)}</div></div>;}
export function Accounts({source,accounts=[],onUpdate}){const [username,setUsername]=useState(''),[busy,setBusy]=useState(false),{toast}=useStudio();const placeholder={reels:'인스타그램 계정명 (예: runwayapp)',x:'X(트위터) 계정명 (예: OpenAI)',threads:'스레드 계정명 (예: openai)',tiktok:'틱톡 계정명 (@ 없이, 예: khaby.lame)'}[source];async function update(action,name){if(busy||!name.trim())return;setBusy(true);try{await toolApi('trends',`/api/${source}/accounts`,{method:'POST',body:{action,username:name.trim().replace(/^@/,'')}});setUsername('');await onUpdate();}catch(e){toast(e.message);}finally{setBusy(false);}}return <><h2 style={{fontSize:16,marginBottom:10}}><I name="user"/> 구독 계정</h2><div className="account-manager"><div className="acc-chips">{accounts.length?accounts.map(account=>{const name=typeof account==='string'?account:account.username||account.account;return <span className="acc-chip" key={name}>@<b>{name}</b><button type="button" title="삭제" aria-label={`${name} 계정 삭제`} disabled={busy} onClick={()=>update('remove',name)}>✕</button></span>;}):<span className="empty-state">아직 저장된 계정이 없습니다.</span>}</div><form className="addbar" onSubmit={e=>{e.preventDefault();void update('add',username);}}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder={placeholder} aria-label={placeholder} maxLength={100}/><button type="submit" disabled={busy}>계정 추가</button></form></div></>;}
export function Discovery({keyword,country,onClose}){const dialog=useRef(),[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{dialog.current.showModal();const controller=new AbortController();toolApi('trends','/_studio/discovery?'+new URLSearchParams({keyword,country}),{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[keyword,country]);return <dialog ref={dialog} className="keyword-discovery" aria-labelledby="discovery-title" onClose={onClose}><header><div><h2 id="discovery-title">{keyword} · SNS 관련 영상</h2><p>YouTube·Shorts는 키워드 검색, TikTok은 수집 영상 내 검색입니다.</p></div><button type="button" aria-label="관련 영상 닫기" onClick={()=>dialog.current.close()}>닫기</button></header><div data-discovery-results aria-live="polite">{data?data.sources.map(source=><section key={source.label}><div className="discovery-source"><h3>{source.label}</h3><a href={safeUrl(source.searchUrl)} target="_blank" rel="noopener noreferrer">직접 검색 ↗</a></div><p>{source.scope}{source.note?' · '+source.note:''}</p><div className="discovery-grid">{source.items.map((item,i)=><a key={i} className="discovery-card" href={safeUrl(item.url)} target="_blank" rel="noopener noreferrer">{item.thumbnail&&<img src={thumb(item.thumbnail)} loading="lazy" alt=""/>}<strong>{item.title}</strong><span>{item.author}</span></a>)}</div></section>):error||'관련 영상을 조회하고 있습니다…'}</div></dialog>;}
export function Player({item,onClose}){const ref=useRef();useEffect(()=>{ref.current.showModal();},[]);return <dialog ref={ref} id="modal" className="open" aria-label="영상 재생" onClose={onClose} onClick={e=>{if(e.target===e.currentTarget)ref.current.close();}}><div className={'modal-box'+(item.vertical?' vertical':'')}><iframe className="player" title={item.title||'영상 재생'} src={'https://www.youtube.com/embed/'+encodeURIComponent(item.videoId)+'?autoplay=1'} allow="autoplay; encrypted-media" allowFullScreen/><div className="modal-actions"><a href={safeUrl(item.url)} target="_blank" rel="noopener noreferrer">유튜브에서 열기 ↗</a><button type="button" onClick={()=>ref.current.close()}>닫기</button></div></div></dialog>;}
