'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { usePathname } from 'next/navigation';
import { api } from '../_lib/api';
import { toolApi, safeUrl } from '../_lib/integration-api';
import { Badge, Button, Field, PageHeading } from './Primitives';
import { useStudio } from './StudioProvider';
const MODEL_LABELS={planning:['기획 · 트렌드 분석','원고와 트렌드 분석에 사용할 대화 모델'],chat:['대화 · 캐릭터 · 컷 편집','캐릭터 설정 대화와 ShortGPT 장면 수정에 사용할 모델'],image:['이미지 · 캐릭터 시트','GPT는 이미지 기획 모델을 선택합니다. 실제 렌더링은 gpt-image-2입니다.'],video:['영상 생성','현재 연결된 영상 생성 경로는 Grok OAuth입니다.']};
const GOOGLE_MESSAGES={connected:'Google 연결이 완료되었습니다. YouTube 채널을 확인할 수 있어요.',access_denied:'Google 연결을 취소했습니다. 원할 때 다시 연결할 수 있어요.',authorization_failed:'Google에서 연결을 승인하지 않았습니다. OAuth 앱 설정을 확인해주세요.',state_invalid:'연결 요청이 만료되었거나 시작한 브라우저와 다릅니다. 이 화면에서 다시 연결해주세요.',scope_required:'YouTube 계정 조회 권한을 허용해야 채널을 연결할 수 있습니다.',refresh_required:'지속 연결 권한을 받지 못했습니다. Google에 다시 연결해주세요.',token_failed:'인증을 완료하지 못했습니다. Google 클라이언트 ID·시크릿과 등록한 콜백 URL을 확인해주세요.',network_error:'Google 서버에 연결하지 못했습니다. 잠시 후 다시 시도해주세요.',youtube_api_error:'채널을 조회하지 못했습니다. Google Cloud에서 YouTube Data API v3 활성화 상태와 할당량을 확인해주세요.',storage_error:'연결 정보를 저장하지 못했습니다. 서버의 파일 접근 권한을 확인해주세요.',cancelled:'연결 요청이 취소되거나 다른 연결로 바뀌었습니다. 다시 시작해주세요.',failed:'Google 연결을 완료하지 못했습니다. 다시 시도해주세요.'};
export function Settings({active}){
 const {user}=useStudio(),[version,setVersion]=useState(0);
 useEffect(()=>{if(active)setVersion(v=>v+1);},[active]);
 return <div className="studio-page"><PageHeading eyebrow="CONNECTED TO YOUR IMAGINATION" index="06 / SETTINGS" title="계정을 연결하고, 제작을 이어가세요" description="AI 계정과 YouTube 채널을 연결하고 작업실의 기본 AI를 관리합니다." actions={<Button variant="secondary" icon="refresh" onClick={()=>setVersion(v=>v+1)}>상태 새로고침</Button>}/>{user.role==='admin'&&<><div className="settings-grid">{['gpt','grok'].map(provider=><ProviderCard key={provider} provider={provider} version={version}/>)}</div><MetaSettings version={version}/></>}<GoogleSettings version={version}/><section className="surface-card settings-card settings-preference"><h2>작업별 AI 모델</h2><p className="small muted">제공자와 모델을 작업별로 저장합니다. 제작 화면에서는 개별 작업의 모델을 다시 선택할 수 있습니다.</p><ModelSettings version={version}/></section><p className="subtitle small">{user.role==='admin'?'AI 계정의 연결 정보는 이 Mac의 기존 OAuth 저장소에서 관리합니다. 로그인 완료 후 다른 기기에서도 같은 작업실을 사용할 수 있습니다.':'AI 생성은 관리자가 연결한 GPT·Grok 계정을 사용합니다. 내 YouTube 연결과 모델 선택은 내 작업실에 저장됩니다.'}</p><McpSettings version={version}/><AccountSettings/></div>;
}
function ProviderCard({provider,version}){
 const {toast}=useStudio(),name=provider==='gpt'?'GPT':'Grok';
 const [auth,setAuth]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[flow,setFlow]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false), generation=useRef(0);
 const refresh=useCallback(async()=>{try{const [oauth,ai]=await Promise.all([toolApi('ima2','/api/oauth/status'),api('/api/ai/status')]);setAuth(provider==='gpt'?oauth.auth:oauth.grokAuth);setReady(ai.providers[provider]?.ready);setError('');}catch(e){setError(e.message);}},[provider]);
 useEffect(()=>{void refresh();},[refresh,version]);
 useEffect(()=>{if(!flow)return;let live=true,timer;const poll=async()=>{if(Date.now()>=flow.expires){setFlow(null);setNotice('인증 코드가 만료되었습니다. 다시 로그인해주세요.');return;}try{const result=await toolApi('ima2',`/api/auth/switch/${encodeURIComponent(flow.sessionId)}`,{timeout:15000});if(!live)return;if(result.status==='complete'){setFlow(null);setNotice('OAuth 연결을 완료했습니다.');toast('OAuth 연결을 완료했습니다.');void refresh();document.dispatchEvent(new Event('oauth-updated'));return;}if(['error','expired'].includes(result.status)){setFlow(null);setNotice(result.error||'인증이 만료되었습니다. 다시 시도해주세요.');return;}setNotice(`로그인 대기 중 · 약 ${Math.max(1,Math.ceil((flow.expires-Date.now())/60000))}분 남음`);}catch(e){if(live)setNotice(`${e.message} 연결 상태를 다시 확인하고 있습니다.`);}if(live)timer=setTimeout(poll,2500);};timer=setTimeout(poll,2000);return()=>{live=false;clearTimeout(timer);};},[flow,refresh,toast]);
 async function login(){setBusy(true);setNotice('인증 코드를 준비하고 있습니다…');const run=++generation.current;try{const result=await toolApi('ima2','/api/auth/switch',{method:'POST',body:{provider:provider==='gpt'?'codex':'grok',flow:'device'},timeout:70000});if(run!==generation.current)return;const url=safeUrl(result.verificationUrl);if(!url||!result.userCode)throw Error('인증 주소를 받지 못했습니다. 다시 시도해주세요.');setFlow({...result,verificationUrl:url,expires:Date.now()+(result.expiresIn||900)*1000});setNotice('로그인 완료를 기다리고 있습니다.');}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 async function cancel(){++generation.current;const current=flow;setFlow(null);try{await toolApi('ima2',`/api/auth/switch/${encodeURIComponent(current.sessionId)}`,{method:'DELETE',timeout:15000});setNotice('로그인을 취소했습니다.');}catch(e){setNotice(e.message);}}
 return <section className="surface-card settings-card" data-provider={provider}><div className="provider-heading"><div><p className="eyebrow">{name.toUpperCase()} OAUTH</p><h2>{name} 계정</h2></div><Badge tone={ready?'pine':'ochre'}>{error?'확인 실패':ready?'연결됨':auth?.loggedIn?'연결 확인 필요':'로그인 필요'}</Badge></div><p className="provider-account">{error||[auth?.email||(auth?.loggedIn?'저장된 OAuth 계정':'연결된 계정이 없습니다.'),auth?.plan,!ready&&auth?.loggedIn?'세션을 확인하지 못했습니다. 다시 로그인하거나 상태를 새로고침하세요.':''].filter(Boolean).join(' · ')}</p>{flow?<div className="notice"><p>인증 페이지를 열고 아래 코드를 입력해주세요.</p><strong className="login-code">{flow.userCode}</strong><div className="login-actions"><a className="primary button" href={flow.verificationUrl} target="_blank" rel="noopener noreferrer">인증 페이지 열기 ↗</a><Button variant="secondary" onClick={()=>copy(flow.userCode,toast)}>코드 복사</Button><Button variant="quiet-button" onClick={cancel}>취소</Button></div><p className="small" role="status">{notice}</p></div>:notice&&<p className="notice" role="status">{notice}</p>}<Button variant="secondary" disabled={busy||!!flow} onClick={login}>{auth?.loggedIn?'다른 계정으로 로그인':`${name} 로그인`}</Button></section>;
}
async function copy(value,toast){try{await navigator.clipboard.writeText(value);toast('복사했습니다.');}catch{toast('클립보드를 사용할 수 없습니다. 표시된 내용을 선택해 복사해주세요.');}}
function MetaSettings({version}){
 const [status,setStatus]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/api/meta/status').then(setStatus).catch(()=>setError('Instagram 앱 설정 상태를 확인하지 못했습니다. 서버 상태를 확인한 뒤 다시 시도해주세요.'));},[version]);const labels={present:'입력됨',missing:'미입력',invalid:'형식 확인 필요'};
 return <section className="surface-card settings-card settings-preference"><div className="provider-heading"><div><p className="eyebrow">INSTAGRAM</p><h2>Instagram 연결 준비</h2></div><Badge tone="ochre">{error?'확인 실패':status?.status==='credentials_present'?'앱 설정 준비됨 · 계정 미연결':'앱 설정 필요'}</Badge></div><p role="status">{error||status?.message||'앱 설정 상태를 확인하고 있어요.'}</p><p className="small muted">{status&&`앱 ID: ${labels[status.credentials.appId]} · 앱 시크릿: ${labels[status.credentials.appSecret]}`}</p><p className="small muted">Facebook 페이지에 연결된 비즈니스·크리에이터 계정이 필요합니다. 계정 연결과 수집·성과 조회·게시 기능은 아직 준비 중입니다.</p></section>;
}
function GoogleSettings({version}){
 const {toast}=useStudio(),pathname=usePathname(),[status,setStatus]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{try{setStatus(await api('/api/google/status'));setError('');}catch{setError('Google 연결 상태를 확인하지 못했습니다. 서버 상태를 확인한 뒤 상태 새로고침을 눌러주세요.');}},[]);
 useEffect(()=>{void refresh();},[version,refresh]);useEffect(()=>{const match=/^\/settings\/google\/([a-z_]+)/.exec(pathname);if(match)setNotice(GOOGLE_MESSAGES[match[1]]||GOOGLE_MESSAGES.failed);},[pathname]);
 async function perform(action){if(busy)return;setBusy(true);try{await action();}catch(e){setNotice(e.message);}finally{setBusy(false);await refresh();}}
 const count=value=>value==null?'비공개 / 제공 안 됨':/^\d+$/.test(String(value))?BigInt(value).toLocaleString('ko-KR'):'제공 안 됨';
 const connected=status?.accountConnected,ready=status?.credentials.clientId&&status?.credentials.clientSecret;
 return <section className="surface-card settings-card settings-preference google-settings" aria-label="Google · YouTube 연결">{!status?<><h2>Google · YouTube 연결</h2><p role="status">{error||'연결 상태를 확인하고 있어요.'}</p></>:<><div className="provider-heading"><div><p className="eyebrow">GOOGLE · YOUTUBE</p><h2>내 YouTube 채널</h2></div><Badge tone={connected?'pine':'ochre'}>{connected?'연결됨':status.status==='reconnect_required'?'다시 연결 필요':ready?'연결 대기':'앱 설정 필요'}</Badge></div><p>{connected?'연결한 YouTube 채널의 공개 통계를 확인합니다.':ready?'Google에 로그인하고 조회할 YouTube 채널의 접근을 허용해주세요.':'서버에 GOOGLE_CLIENT_ID와 GOOGLE_CLIENT_SECRET을 입력하고 재시작해주세요.'}</p>{(notice||error)&&<p className="notice" role="status">{notice||error}</p>}<div className="google-channels">{connected&&(status.channels.length?status.channels.map(channel=><div key={channel.id} className="google-channel"><a href={channel.url} target="_blank" rel="noopener noreferrer">{channel.title||channel.id} ↗</a><dl className="google-statistics">{[['누적 조회수','views'],['구독자','subscribers'],['공개 영상','videos']].map(([label,key])=><div key={key}><dt>{label}</dt><dd>{count(channel.statistics[key])}</dd></div>)}</dl></div>):<p className="small muted">이 계정에 연결된 YouTube 채널이 없습니다. 다른 Google 계정 또는 브랜드 채널로 연결해주세요.</p>)}</div>{status.lastVerifiedAt&&<p className="small muted">마지막 조회: {new Date(status.lastVerifiedAt).toLocaleString('ko-KR')} · 구독자 수는 YouTube가 제공하는 반올림 수치입니다.</p>}<div className="login-actions"><Button variant="secondary" disabled={!ready||busy} onClick={()=>perform(async()=>{const flow=await api('/api/google/connect','POST',{}),url=new URL(flow.authorizationUrl);if(url.origin!=='https://accounts.google.com'||url.pathname!=='/o/oauth2/v2/auth')throw Error('Google 인증 주소를 확인하지 못했습니다.');location.assign(url.href);})}>{connected?'다른 채널 연결':'Google로 연결'}</Button>{connected&&<Button variant="secondary" disabled={busy} onClick={()=>perform(async()=>{await api('/api/google/channels');setNotice('YouTube 채널 통계를 새로 불러왔습니다.');})}>채널 통계 새로고침</Button>}{status.canDisconnect&&<Button variant="quiet-button" disabled={busy} onClick={()=>perform(async()=>{await api('/api/google/disconnect','POST',{});setNotice('Google 접근 권한을 해제하고 저장된 연결 정보를 삭제했습니다.');})}>연결 해제</Button>}</div><details className="google-setup"><summary>Google 앱 설정 · 콜백 URL</summary><p className="small muted">Google Cloud의 웹 애플리케이션 OAuth 클라이언트 → 승인된 리디렉션 URI에 아래 주소를 등록해주세요. 접속 주소가 바뀌면 해당 주소도 등록해야 합니다.</p><Field label="현재 접속 주소의 콜백 URL" aria-label="Google 콜백 URL" value={status.callbackUrl} readOnly/><Button variant="secondary" onClick={()=>copy(status.callbackUrl,toast)}>콜백 URL 복사</Button><p className="small muted">클라이언트 ID: {status.credentials.clientId?'입력됨':'미입력'} · 클라이언트 시크릿: {status.credentials.clientSecret?'입력됨':'미입력'} · YouTube API 키: {status.credentials.apiKey?'입력됨':'미입력'}</p><p className="small muted">YouTube Data API v3를 활성화하고, OAuth 앱이 테스트 상태이면 로그인할 Google 계정을 테스트 사용자로 추가해주세요. 공개 검색용 API 키는 이 계정 연결에 필요하지 않습니다.</p></details></>}</section>;
}
function ModelSettings({version}){
 const {toast}=useStudio(),[settings,setSettings]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/api/ai/settings').then(setSettings).catch(e=>setError(e.message));},[version]);
 function change(role,key,value){setSettings(s=>{const selected={...s.roles[role],[key]:value};if(key==='provider')selected.model=s.catalog[role][value][0]?.id;return {...s,roles:{...s.roles,[role]:selected}};});}
 async function save(e,role){e.preventDefault();setBusy(true);try{setSettings(await api('/api/ai/settings','PUT',{role,value:settings.roles[role],revision:settings.revision}));toast(`${MODEL_LABELS[role][0]} 모델을 저장했습니다.`);document.dispatchEvent(new Event('ai-settings-updated'));}catch(e){toast(e.message);}finally{setBusy(false);}}
 return <div id="model-settings" aria-live="polite">{settings?Object.entries(MODEL_LABELS).map(([role,[title,description]])=>{const selected=settings.roles[role],options=settings.catalog[role][selected.provider].map(m=>({value:m.id,label:m.label||m.id}));if(selected.model&&!options.some(o=>o.value===selected.model))options.unshift({value:selected.model,label:`${selected.model} (현재 목록에서 확인되지 않음)`});return <form key={role} className="model-role" onSubmit={e=>save(e,role)}><div><h3>{title}</h3><p className="small muted">{description}</p></div><Field label="AI 제공자" name="provider" value={selected.provider} disabled={busy} onChange={v=>change(role,'provider',v)} options={Object.keys(settings.catalog[role]).map(id=>({value:id,label:id==='gpt'?'GPT OAuth':'Grok OAuth'}))}/><Field label={role==='image'&&selected.provider==='gpt'?'이미지 기획 모델':'사용할 모델'} name="model" value={selected.model} disabled={busy} onChange={v=>change(role,'model',v)} options={options}/><Button type="submit" variant="secondary" disabled={busy}>저장</Button></form>;}):error||'모델 목록을 불러오고 있습니다…'}</div>;
}
function McpSettings({version}){
 const {toast}=useStudio(),[status,setStatus]=useState(null),[entries,setEntries]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const grants=useCallback(async()=>{setEntries((await api('/api/oauth/grants')).grants);},[]);useEffect(()=>{Promise.all([api('/api/mcp/status').then(setStatus),grants()]).catch(e=>setError(e.message));},[version,grants]);
 async function revoke(id){setBusy(id);try{await api('/api/oauth/grants/revoke','POST',{id});await grants();toast('MCP 연결을 해제했습니다.');}catch(e){toast(e.message);}finally{setBusy('');}}
 return <section className="surface-card settings-card settings-preference"><p className="eyebrow">CONNECTED WORKFLOWS</p><h2>MCP · Claude와 Codex 연결</h2>{status?<><p>웹 계정으로 로그인하고 연결을 승인하면 내 캐릭터·시나리오·이미지·영상 노드를 대화로 다룰 수 있습니다.</p><p className="small muted">{status.toolCount}개 도구 · OAuth + PKCE</p><Field label="MCP 접속 주소" value={status.endpoint} readOnly/><div className="story-actions"><Button variant="secondary" onClick={()=>copy(`codex mcp add snowlink-studio --url ${status.endpoint}\ncodex mcp login snowlink-studio`,toast)}>Codex 연결 명령 복사</Button><Button variant="secondary" onClick={()=>copy(`claude mcp add --transport http snowlink-studio ${status.endpoint}\nclaude mcp login snowlink-studio`,toast)}>Claude Code 연결 명령 복사</Button></div><p className="small muted">앱에서 URL을 추가한 뒤 로그인 버튼을 눌러도 됩니다. Claude Code에서는 /mcp 메뉴에서도 인증할 수 있습니다. Tailscale 주소에 접근 가능한 기기에서 연결하세요. Claude 웹의 클라우드 커넥터에는 외부에서 접근 가능한 HTTPS 주소가 필요합니다.</p><h3>승인한 연결</h3><div>{entries.length?entries.map(g=><div className="story-job" key={g.id}><div><strong>{g.clientName}</strong><p>{new Date(g.createdAt).toLocaleDateString('ko-KR')} 승인</p></div><Button variant="secondary" disabled={busy===g.id} onClick={()=>revoke(g.id)}>연결 해제</Button></div>):<p className="small muted">승인한 MCP 연결이 없습니다.</p>}</div><details><summary>고급 · 이 Mac의 로컬 프로세스로 연결</summary><p className="small muted">로컬 stdio 연결은 이 Mac의 계정별 연결 파일을 사용합니다. OAuth 로그인을 사용하려면 위 URL 방식으로 연결하세요.</p><Button variant="secondary" onClick={()=>copy(JSON.stringify({mcpServers:{'snowlink-studio':status.stdio}},null,2),toast)}>로컬 설정 복사</Button></details></>:<p>{error||'연결 정보를 불러오고 있습니다…'}</p>}</section>;
}
function AccountSettings(){
 const {user,toast}=useStudio(),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();const form=e.currentTarget,values=Object.fromEntries(new FormData(form));if(values.password!==values.confirm)return toast('새 비밀번호 확인이 일치하지 않습니다.');setBusy(true);try{await api('/api/auth/password','POST',{currentPassword:values.currentPassword,password:values.password});form.reset();toast('비밀번호를 변경했습니다.');}catch(e){toast(e.message);}finally{setBusy(false);}}
 return <section className="surface-card settings-card settings-preference"><p className="eyebrow">MY ACCOUNT</p><h2>{user.name} · 계정</h2><p className="muted">아이디: {user.username}</p><details><summary>비밀번호 변경</summary><form onSubmit={submit}>{[['currentPassword','현재 비밀번호'],['password','새 비밀번호'],['confirm','새 비밀번호 확인']].map(([name,label])=><label className="field" key={name}><span>{label}</span><input name={name} type="password" autoComplete={name==='currentPassword'?'current-password':'new-password'} minLength={name==='currentPassword'?undefined:10} maxLength={128} required/></label>)}<p className="small muted">변경하면 다른 기기의 로그인 세션이 해제됩니다.</p><Button type="submit" variant="secondary" disabled={busy}>비밀번호 변경</Button></form></details></section>;
}
